packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': true
  '@reown/appkit': true
  bigint-buffer: true
  bufferutil: true
  esbuild: true
  prisma: true
  protobufjs: true
  unrs-resolver: true
  utf-8-validate: true
